sudo: required
services:
  - docker
before_install:
  - docker build -t imparaai/go-figure-api .
  - docker run -d imparaai/go-figure-api
script:
  - docker exec api sh -c "go test ./..."
notifications:
  email:
    on_success: never