sudo: required
services:
  - docker
before_install:
  - docker-compose up -d
  - sleep 10
script:
  - docker-compose exec api /bin/sh -c "go test -v ./.../test"
deploy:
  proivder: script
  script: bash dockerhub_push
  on:
    branch: master
notifications:
  email:
    on_success: never