sudo: required
services:
  - docker
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
cache:
  directories:
  - $HOME/google-cloud-sdk
before_script:
  - docker build --target builder -t imparaai/go-figure-api:dev .
  - docker build -t imparaai/go-figure-api .
  - docker-compose up -d
  - sleep 10
script:
  - docker-compose exec api /bin/sh -c "go test -v ./.../test"
deploy:
  provider: script
  script: bash deploy
  on:
    branch: master
notifications:
  email:
    on_success: never