sudo: required
services:
  - docker
before_install:
  - docker-compose up -d
  - sleep 10
script:
  - docker-compose exec api /bin/sh -c "go test -v ./.../test"
notifications:
  email:
    on_success: never