sudo: required
services:
  - docker
before_install:
  - docker build -t imparaai/go-figure-api .
script:
  - docker run imparaai/go-figure-api sh -c "go test ./..."
notifications:
  email:
    on_success: never