#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push imparaai/go-figure-api

if [ ! -d $HOME/google-cloud-sdk/bin ]; then
  rm -rf $HOME/google-cloud-sdk;
  curl https://sdk.cloud.google.com | bash > /dev/null;
fi

source $HOME/google-cloud-sdk/path.bash.inc
gcloud components update kubectl

ls -la .

gcloud auth activate-service-account --key-file gce-deploy-service-account.json

gcloud container clusters get-credentials go-figure --zone us-central1-a --project imparaai-sergio
gcloud auth configure-docker